FROM python:3

WORKDIR /usr/src/app
COPY requirements.txt ./
COPY azure_helper.py ./
COPY automated_label_prop.py ./
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "python", "./automated_label_prop.py" ]