FROM python:3

WORKDIR /usr/src/app
COPY requirements.txt ./
COPY azure_helper.py ./
COPY modeling.py ./
COPY predict_labels.py ./
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "python", "./predict_labels.py" ]